// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klyzxqgpnsujuyllokgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtseXp4cWdwbnN1anV5bGxva2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2ODM0ODcsImV4cCI6MjA1NjI1OTQ4N30.F_16pNMxeyL1nfn1sarCgGPNKjljfqG5hxAG8lU8JPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);